spring:
  # Spring AI
  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: gpt-4
        api-key: ${OPEN_AI_API_KEY}

    mistralai:
      api-key: ${MISTRAL_AI_API_KEY}
      chat:
        options:
          model: mistral-small-latest

  threads:
    virtual:
      enabled: true
  main:
    web-application-type: none
    banner-mode: off