spring:
  # Spring AI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4

    mistralai:
      api-key: ${MISTRAL_AI_API_KEY}
      chat:
        options:
          model: mistral-large-latest


    vectorstore:
      pgvector:
        dimensions: 1536

  threads:
    virtual:
      enabled: true