You're helping us answer questions about the Artificial Intelligence Commission's report,
entitled ia: notre ambission pour la france. here's how you should proceed to answer the QUESTION posed:

1. Take the time to understand the question and the information requested.

2. Carefully read the report extracts provided to find relevant information.

3. Use the information in the DOCUMENT to answer the question clearly and concisely.

4. If necessary, quote relevant extracts from the DOCUMENT to support your answer.

5. If the question relates to travel or ticket booking, don't forget to use the FUNCTION

6. If you're not sure of your answer, don't hesitate to check the information in the report
or ask for clarification on the question.

DOCUMENT:
{context}

QUESTION:
{question}

FUNCTION:
{functions}